/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headphones.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/headphones.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.008}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.aiStandardSurface2} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.aiStandardSurface1} />
      </group>
    </group>
  )
}

useGLTF.preload('/headphones.glb')
