/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/headphonesHighpoly.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D/headphonesHighpoly.glb')

  const textures = useTexture({
    map: '/3D/textures/1.jpeg',
    normalMap: '/3D/textures/2.jpeg',
    roughnessMap: '/3D/textures/3.jpeg',
  })

  // Apply textures to material
  React.useLayoutEffect(() => {
    if (materials.Material) {
      materials.Material.map = textures.map
      materials.Material.normalMap = textures.normalMap
      materials.Material.roughnessMap = textures.roughnessMap
      materials.Material.needsUpdate = true
    }
  }, [materials, textures])

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Headphones_001_high.geometry} material={materials.Material} position={[0, 0, -1.184]} />
        <mesh geometry={nodes.Headphones_002_high.geometry} material={materials.Material} position={[0, 0, -0.919]} />
        <mesh geometry={nodes.Headphones_003_high.geometry} material={materials.Material} position={[0, 0, -0.542]} />
        <mesh geometry={nodes.Headphones_004_high.geometry} material={materials.Material} position={[0, 0, -0.288]} />
        <mesh geometry={nodes.Headphones_005_high.geometry} material={materials.Material} position={[0, 0, -0.333]} />
        <mesh geometry={nodes.Headphones_006_high.geometry} material={materials.Material} position={[0, 0, -0.361]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3D/headphonesHighpoly.glb')
