/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { useGLTF, Environment, Float } from '@react-three/drei';

function Model({ scrollProgress, ...props }) {
  const { nodes, materials } = useGLTF('/3d/arcade_Low.glb');
  const group = useRef();
  const { viewport } = useThree();

  useFrame((state) => {
    if (group.current) {
      // Ambient floating rotation
      const time = state.clock.getElapsedTime();

      // Base rotation (Arcade machine usually faces front, maybe slight rotation?)
      let targetRotationY = time * 0.1; // Slow spin

      // Add scroll influence if available
      if (scrollProgress) {
        // Get current scroll value (0 to 1)
        const currentScroll = scrollProgress.get();

        // ROTATION:
        // Full spin feels a bit much for an arcade, maybe just 360 or 720?
        // Let's stick to the requested "Same animations"
        targetRotationY += currentScroll * Math.PI * 4;

        // POSITION (Arc Movement):
        // X: Linear movement from Left (-35% viewport) to Right (+35% viewport)
        const x = (currentScroll - 0.5) * (viewport.width * 0.7);

        // Y: Parabolic arc
        const baseY = -viewport.height * 0.3;
        const peakHeight = viewport.height * 0.4;
        const y = baseY + Math.sin(currentScroll * Math.PI) * peakHeight;

        group.current.position.set(x, y, 0);

        // SCALE:
        // Grow from base scale
        const baseScale = 5; // Headphones had 5. Arcade might need different base scale.
        // The GLB import has scale={0.01} on inner group.
        // If we scale the outer group, we multiply that.
        // Headphones inner scale was 0.4.
        // Let's try baseScale 3 for now, user can adjust.
        const scale = baseScale * (1 + currentScroll * 1.5);
        group.current.scale.setScalar(scale);
      }

      // Apply rotation smoothly
      group.current.rotation.y = targetRotationY;

      // Subtle tilt
      group.current.rotation.x = Math.sin(time * 0.5) * 0.05;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Inner group from gltfjsx with Original transforms */}
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.ArcadeLow_Body.geometry} material={materials.standardSurface1} position={[0, 0.112, -5.159]} />
        <mesh geometry={nodes.ArcadeLow_Button_A.geometry} material={materials.standardSurface1} position={[0.713, -1.278, -5.443]} />
        <mesh geometry={nodes.ArcadeLow_Button_B.geometry} material={materials.standardSurface1} position={[0.557, -1.112, -5.483]} />
        <mesh geometry={nodes.ArcadeLow_Button_C.geometry} material={materials.standardSurface1} position={[0.409, -1.278, -5.443]} />
        <mesh geometry={nodes.ArcadeLow_Button_D.geometry} material={materials.standardSurface1} position={[0.557, -1.437, -5.404]} />
        <mesh geometry={nodes.ArcadeLow_Button_E.geometry} material={materials.standardSurface1} position={[-0.936, -1.112, -5.483]} />
        <mesh geometry={nodes.ArcadeLow_Button_F.geometry} material={materials.standardSurface1} position={[-0.78, -1.278, -5.443]} />
        <mesh geometry={nodes.ArcadeLow_Button_G.geometry} material={materials.standardSurface1} position={[-1.084, -1.278, -5.443]} />
        <mesh geometry={nodes.ArcadeLow_Button_H.geometry} material={materials.standardSurface1} position={[-0.936, -1.437, -5.404]} />
        <mesh geometry={nodes.ArcadeLow_Glass.geometry} material={materials.standardSurface1} position={[0, 2.798, -1.557]} />
        <mesh geometry={nodes.ArcadeLow_Handle_A.geometry} material={materials.standardSurface1} position={[-0.406, -1.279, -5.441]} />
        <mesh geometry={nodes.ArcadeLow_Handle_B.geometry} material={materials.standardSurface1} position={[1.087, -1.279, -5.441]} />
        <mesh geometry={nodes.ArcadeLow_Screen.geometry} material={materials.standardSurface1} position={[0, -0.133, -7.277]} />
      </group>
    </group>
  );
}

useGLTF.preload('/3d/arcade_Low.glb');

export default function ArcadeLowModel({ scrollProgress, className = "w-full h-full" }) {
  return (
    <div className={className}>
      <Canvas camera={{ position: [0, 0, 10], fov: 45 }} gl={{ alpha: true }}>
        <ambientLight intensity={1} />
        <spotLight position={[10, 10, 10]} angle={0.5} penumbra={1} intensity={2} color="#ffffff" />
        <pointLight position={[-10, -10, -10]} intensity={2} color="#3b82f6" />

        <Float speed={2} rotationIntensity={0.5} floatIntensity={0.5}>
          <Model scrollProgress={scrollProgress} />
        </Float>

        <Environment preset="city" />
      </Canvas>
    </div>
  );
}
