/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headphones.glb 
*/

import React, { useRef, useLayoutEffect } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { useGLTF, useTexture, Environment, Float } from '@react-three/drei';
import * as THREE from 'three';

function Model({ scrollProgress, ...props }) {
    const { nodes, materials } = useGLTF('/3d/headphonesHighpoly.glb?v=final');
    const group = useRef();
    const { viewport } = useThree();

    const textures = useTexture({
        map: '/3d/textures/2.jpeg?v=final',
        normalMap: '/3d/textures/3.jpeg?v=final',
        roughnessMap: '/3d/textures/1.jpeg?v=final',
    })

    // Apply textures to material
    useLayoutEffect(() => {
        // Texture Settings

        // 1. Map (Color) -> sRGB, FlipY False (Standard for GLB)
        if (textures.map) {
            textures.map.flipY = false;
            textures.map.colorSpace = THREE.SRGBColorSpace;
        }

        // 2. Normal/Roughness -> Linear (Non-Color), FlipY False
        [textures.normalMap, textures.roughnessMap].forEach(t => {
            if (t) {
                t.flipY = false;
                t.colorSpace = THREE.LinearSRGBColorSpace; // Critical: distinct from sRGB
            }
        });

        if (materials.Material) {
            // Reset base parameters
            materials.Material.color = new THREE.Color(0xffffff); // White base
            materials.Material.metalness = 1.0; // Headphones usually metal/plastic
            materials.Material.roughness = 1.0; // Driven by map

            // Assign Maps
            materials.Material.map = textures.map;
            materials.Material.normalMap = textures.normalMap;
            materials.Material.roughnessMap = textures.roughnessMap;

            materials.Material.needsUpdate = true;
        }
    }, [materials, textures])

    useFrame((state) => {
        if (group.current) {
            // Ambient floating rotation
            const time = state.clock.getElapsedTime();

            // Base rotation
            let targetRotationY = time * 0.2; // Slow constant spin

            // Add scroll influence if available
            if (scrollProgress) {
                // Get current scroll value (0 to 1)
                const currentScroll = scrollProgress.get();

                // ROTATION:
                // Rotate based on scroll: full scroll = 2 full spins (4*PI)
                targetRotationY += currentScroll * Math.PI * 4;

                // POSITION (Arc Movement):
                // X: Linear movement from Left (-35% viewport) to Right (+35% viewport)
                const x = (currentScroll - 0.5) * (viewport.width * 0.7);

                // Y: Parabolic arc using Sine
                // Start/End at bottom (-30% viewport)
                // Peak at top (+10% viewport)
                const baseY = -viewport.height * 0.3;
                const peakHeight = viewport.height * 0.4; // How high it goes from base
                const y = baseY + Math.sin(currentScroll * Math.PI) * peakHeight;

                group.current.position.set(x, y, 0);

                // SCALE:
                // Grow from scale 1 to 1.8 as scroll progresses
                const baseScale = 5;
                const scale = baseScale * (1 + currentScroll * 1.5); // Increase growth factor
                group.current.scale.setScalar(scale);
            }

            // Apply rotation smoothly
            group.current.rotation.y = targetRotationY;

            // Add subtle looking around movement based on mouse/time
            group.current.rotation.x = Math.sin(time * 0.5) * 0.1;
        }
    });

    return (
        <group ref={group} {...props} dispose={null}>
            {/* 
                Reverting to original gltfjsx detected rotation: [Math.PI / 2, 0, 0]
            */}
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.5}>

                <mesh geometry={nodes.Headphones_001_high.geometry} material={materials.Material} position={[0, 0, -1.184]} />
                <mesh geometry={nodes.Headphones_002_high.geometry} material={materials.Material} position={[0, 0, -0.919]} />
                <mesh geometry={nodes.Headphones_003_high.geometry} material={materials.Material} position={[0, 0, -0.542]} />
                <mesh geometry={nodes.Headphones_004_high.geometry} material={materials.Material} position={[0, 0, -0.288]} />
                <mesh geometry={nodes.Headphones_005_high.geometry} material={materials.Material} position={[0, 0, -0.333]} />
                <mesh geometry={nodes.Headphones_006_high.geometry} material={materials.Material} position={[0, 0, -0.361]} />
            </group>
        </group>
    );
}

export default function HeadphonesModel({ scrollProgress, className = "w-full h-full" }) {
    return (
        <div className={className}>
            <Canvas camera={{ position: [0, 0, 10], fov: 45 }} gl={{ alpha: true }}>
                <ambientLight intensity={1} />
                <spotLight position={[10, 10, 10]} angle={0.5} penumbra={1} intensity={2} color="#ffffff" />
                <pointLight position={[-10, -10, -10]} intensity={2} color="#3b82f6" />

                <Float speed={2} rotationIntensity={0.5} floatIntensity={0.5}>
                    <Model scrollProgress={scrollProgress} />
                </Float>

                <Environment preset="city" />
            </Canvas>
        </div>
    );
}

useGLTF.preload('/3d/headphonesHighpoly.glb?v=final');
