/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headphones.glb 
*/

import React, { useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { useGLTF, Environment, Float } from '@react-three/drei';
import * as THREE from 'three';

function Model({ scrollProgress, ...props }) {
    const { nodes, materials } = useGLTF('/3d/headphones.glb');
    const group = useRef();
    const { viewport } = useThree();

    useFrame((state) => {
        if (group.current) {
            // Ambient floating rotation
            const time = state.clock.getElapsedTime();

            // Base rotation
            let targetRotationY = time * 0.2; // Slow constant spin

            // Add scroll influence if available
            if (scrollProgress) {
                // Get current scroll value (0 to 1)
                const currentScroll = scrollProgress.get();

                // ROTATION:
                // Rotate based on scroll: full scroll = 2 full spins (4*PI)
                targetRotationY += currentScroll * Math.PI * 4;

                // POSITION (Arc Movement):
                // X: Linear movement from Left (-35% viewport) to Right (+35% viewport)
                const x = (currentScroll - 0.5) * (viewport.width * 0.7);

                // Y: Parabolic arc using Sine
                // Start/End at bottom (-30% viewport)
                // Peak at top (+10% viewport)
                const baseY = -viewport.height * 0.3;
                const peakHeight = viewport.height * 0.4; // How high it goes from base
                const y = baseY + Math.sin(currentScroll * Math.PI) * peakHeight;

                group.current.position.set(x, y, 0);

                // SCALE:
                // Grow from scale 1 to 1.8 as scroll progresses
                const scale = 1 + currentScroll * 0.8;
                group.current.scale.setScalar(scale);
            }

            // Apply rotation smoothly
            group.current.rotation.y = targetRotationY;

            // Add subtle looking around movement based on mouse/time
            group.current.rotation.x = Math.sin(time * 0.5) * 0.1;
        }
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={1}>
                <mesh geometry={nodes.Mesh.geometry} material={materials.aiStandardSurface2} />
                <mesh geometry={nodes.Mesh_1.geometry} material={materials.aiStandardSurface1} />
            </group>
        </group>
    );
}

export default function HeadphonesModel({ scrollProgress, className = "w-full h-full" }) {
    return (
        <div className={className}>
            <Canvas camera={{ position: [0, 0, 6], fov: 45 }} gl={{ alpha: true }}>
                <ambientLight intensity={0.5} />
                <spotLight position={[10, 10, 10]} angle={0.5} penumbra={1} intensity={2} color="#10b981" />
                <pointLight position={[-10, -10, -10]} intensity={1} color="#3b82f6" />

                <Float speed={2} rotationIntensity={0.5} floatIntensity={0.5}>
                    <Model scrollProgress={scrollProgress} />
                </Float>

                <Environment preset="city" />
            </Canvas>
        </div>
    );
}

useGLTF.preload('/3d/headphones.glb');
